### ISSUE TITLE
NameError: name 'username' is not defined

### ISSUE THREAD

**Issue by rollecode** [ModalSeoul/Ripfm#2]
Hello. Just found WILT, looks cool. Meant to use it as a backup for Last.fm

Getting this:

````
$ python ripfm.py 
Username: rolle
Traceback (most recent call last):
  File "ripfm.py", line 58, in <module>
    Wilt = Wilt()
  File "ripfm.py", line 19, in __init__
    self.user = input('Username: ')
  File "<string>", line 1, in <module>
NameError: name 'rolle' is not defined
````

**Comment by ModalSeoul** [comment]
Hey, sorry just seeing this. That's odd. Let me see if I pushed a booboo.

**Comment by ModalSeoul** [comment]
Ah, run it with Python3. Or change `input` to `raw_input`

**Comment by ModalSeoul** [comment]
Closing this as I assume that did the trick(it should) - If not let me know.

**Comment by rollecode** [comment]
`python3 ripfm.py`:

````
$ python3 ripfm.py 
Failed to import the site module
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 563, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 335, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/site-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
````

Changed `input` to `raw_input`, then `python ripfpm.py`:

````
$ python ripfm.py
Username: rolle
Password: xxxx
Last.fm Username: rolle-
Traceback (most recent call last):
  File "ripfm.py", line 58, in <module>
    Wilt = Wilt()
  File "ripfm.py", line 23, in __init__
    self.header = {'Authorization': 'Token {}'.format(self.login())}
  File "ripfm.py", line 27, in login
    r = post(Auth, data={'username': self.user, 'password': self.password})
  File "/Library/Python/2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)
````

Forgot to let you know I'm on **Mac OS X 10.11.6**.

**Comment by ModalSeoul** [comment]
Update requests module? I've never seen this before.
